import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import GlobalState from "./context/page";
import { NextAuthProvider } from "./Providers";
import Footer from "@/components/footer/Footer";
import VoiceAssistant from "@/components/voiceAssistant/VoiceAssistant";


const inter = Inter({ subsets: ["latin"]});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <GlobalState>
        <html lang="en">
          <body className="mx-auto max-w-screen-4xl bg-back relative">
            <Navbar />
            <div className="top-50 right-10 absolute z-40">
              <VoiceAssistant />
              </div>
            <div className="">
              
              {children}
            </div>
            <Footer />
          </body>
        </html>
      </GlobalState>
    </NextAuthProvider>
  );
}
